version: "3.1"

services:
  alan_db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_DATABASE: alan_db
      MYSQL_ROOT_USER: ualan
      MYSQL_USER: ualan
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
